In [1]:
import numpy as np

In [4]:
list1=[1,2]
list2=[2,3]
array1=np.array([list1,list1])
print(array1)
print(array1.shape,array1.size,array1.dtype)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]]
(2, 4) 8 float64


### 矩阵运算

In [14]:
a = np.random.randint(10,size=25).reshape([5,5])
print(a)
b = np.random.randint(10,size=25).reshape([5,5])
print(b)
A  = np.mat(a)
B = np.mat(b)
print(a*b)
print(a@b)
print(A@B)

[[1 3 6 7 1]
 [7 7 5 9 9]
 [7 5 0 9 2]
 [2 9 4 1 7]
 [9 8 3 0 0]]
[[0 0 8 2 7]
 [5 3 4 1 7]
 [3 7 0 5 4]
 [7 0 4 4 9]
 [8 0 6 3 9]]
[[ 0  0 48 14  7]
 [35 21 20  9 63]
 [21 35  0 45  8]
 [14  0 16  4 63]
 [72  0 18  0  0]]
[[ 90  51  54  66 124]
 [185  56 174 109 280]
 [104  15 124  61 183]
 [120  55  98  58 165]
 [ 49  45 104  41 131]]
[[ 90  51  54  66 124]
 [185  56 174 109 280]
 [104  15 124  61 183]
 [120  55  98  58 165]
 [ 49  45 104  41 131]]
