merge and split


In [2]:
import tensorflow as tf
import numpy as np

In [3]:
a=tf.ones([2,3,4])
b=tf.ones([2,3,4])

In [4]:
c=tf.concat([a,b],axis=0)
c=tf.stack([a,b],axis=0)
print(c.shape)
c_unstack=tf.unstack(c,axis=3)
print(len(c_unstack))
c_split=tf.split(c,axis=3,num_or_size_splits=[1,1,2])
print(c_split)

(2, 2, 3, 4)
4
[<tf.Tensor: shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]], dtype=float32)>, <tf.Tensor: shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]], dtype=float32)>, <tf.Tensor: shape=(2, 2, 3, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]], dtype=float32)>]


In [5]:
train_data=tf.constant([[0.7,0.2,0.1],[0.1,0.1,0.8]],dtype=tf.float32)
true_data=tf.constant([0,1],dtype=tf.int32)
label=tf.cast(tf.argmax(train_data,axis=1),dtype=tf.int32)
accruracy=tf.cast(tf.equal(label,true_data),dtype=tf.int32)
accruracy=tf.reduce_sum(accruracy)/2
print(accruracy)
c=tf.constant([1,1,2,3,1])
print(tf.unique(c))

tf.Tensor(0.5, shape=(), dtype=float64)
Unique(y=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 2, 0])>)


In [6]:
def accuracy(out_put,target,topk=(1,)):
    maxk=max(topk)
    batch_size=target.shape[0]
    pre=tf.math.top_k(out_put,maxk).indices
    pre=tf.transpose(pre,perm=[1,0])
    target=tf.broadcast_to(target,pre.shape)
    correct=tf.equal(pre,target)

    res=[]
    for k in topk:
        correct_k=tf.cast(tf.reshape(correct[:k],[-1]),dtype=tf.float32)
        correct_k=tf.reduce_sum(correct_k)
        acc=float(correct_k*(100/batch_size))
        res.append(acc)
    return res

out=tf.random.normal([10,6])
out=tf.math.softmax(out,axis=1)
label=tf.random.uniform([10],maxval=6,dtype=tf.int32,name='label')
print("prob:",out)
pred=tf.argmax(out,axis=1)
acc=accruracy(out,label,(1,2,3,4,5,6))
print(acc)

prob: tf.Tensor(
[[0.16546652 0.17959327 0.10326803 0.42030025 0.09262563 0.03874625]
 [0.09391136 0.03578986 0.1779321  0.34303388 0.20853497 0.1407978 ]
 [0.3019856  0.10071753 0.20770648 0.19023749 0.17044051 0.02891237]
 [0.37321362 0.19475278 0.03564801 0.10379332 0.18259259 0.10999975]
 [0.1294495  0.08144693 0.03701284 0.41795623 0.2316683  0.10246632]
 [0.26111633 0.06045714 0.09316215 0.12167425 0.3302464  0.13334373]
 [0.2731382  0.12983906 0.13506168 0.16866347 0.03921055 0.25408706]
 [0.07051637 0.41651216 0.14677638 0.24933696 0.09491102 0.0219471 ]
 [0.07879455 0.2280074  0.351584   0.0239903  0.07119715 0.24642667]
 [0.01259253 0.10356585 0.0555944  0.511142   0.03188717 0.28521806]], shape=(10, 6), dtype=float32)


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

填充和复制


In [ ]:
aa=tf.pad(a,[[0,0],[1,1],[1,1]])
print(aa)
bb=tf.tile(b,[2,1,1])
print(bb.shape)

张量限幅


In [ ]:
nums=tf.range(10,dtype=tf.int32)
print(tf.maximum(nums,3))

In [ ]:
c=tf.random.normal([3,3],dtype=tf.float32)
print(c)
mask=c>0
print(mask)
indices=tf.where(mask)
print(indices)
res=tf.gather_nd(c,indices=indices)
print(res)

In [ ]:
import matplotlib.pyplot as plt
def fun(x):
    z=tf.math.sin(x[...,0])+tf.math.sin(x[...,1])
    return z

x=tf.linspace(-2.,2,5)
y=tf.linspace(-2.,2,5)
pointx,pointy=tf.meshgrid(x,y)
points=tf.stack([pointx,pointy],axis=2)
z=fun(points)
print(z)
plt.figure('plot 2d func value')
plt.imshow(z,origin='lower',interpolation='none')
plt.colorbar()
plt.figure('plot 2d func,contour')
plt.contour(pointx,pointy,z)
plt.colorbar()
plt.show()

不规则索引



In [20]:
data=tf.random.uniform((4,35,8),maxval=10,dtype=tf.int32)
# 第1,3个班，四
data_select=tf.gather_nd(data,[[[0,3,2],[0,7,4]],[[1,7,0],[1,3,1]],[[2,2,1],[2,3,0]]])
print(data_select)

tf.Tensor(
[[6 9]
 [7 1]
 [5 1]], shape=(3, 2), dtype=int32)
