In [1]:
import tensorflow as tf
import numpy as np

1.dateType of tensorFlow

In [2]:
a=tf.constant(1.)
print(a)
print(a.ndim)
print(a.device)

tf.Tensor(1.0, shape=(), dtype=float32)
0
/job:localhost/replica:0/task:0/device:CPU:0


2.create tensor


In [3]:
b=np.arange(5)
bb=tf.convert_to_tensor(b,dtype=tf.float32)
print(bb)
bbb=tf.cast(bb,dtype=tf.int32)
print(bbb)
b_var=tf.Variable(bb,name='test_arg')
print("name:"+b_var.name)

tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
name:test_arg:0


In [4]:
c=tf.zeros([2,3,3],dtype=tf.int32)
d=tf.zeros_like(c)
print(d)
c=tf.ones([2,3,3],dtype=tf.int32)
print(c)
d=tf.fill([2,3,3],9)
print(d)

tf.Tensor(
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]], shape=(2, 3, 3), dtype=int32)


In [5]:
out=tf.random.uniform([4,10],name='out')
y=tf.range(4)
y=tf.one_hot(y,depth=10)
loss=tf.keras.losses.MSE(y,out)
print(loss)
loss=tf.reduce_mean(loss)
print(loss)


tf.Tensor([0.30537978 0.43311563 0.44157267 0.429691  ], shape=(4,), dtype=float32)
tf.Tensor(0.40243974, shape=(), dtype=float32)


In [6]:
x=tf.random.normal([4,8])
net=tf.keras.layers.Dense(10)
net.build((4,8))
print(net.kernel)  # 所使用的变换举证
print(net(x).shape)
print(net.bias.shape)

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[-0.24405748,  0.28614718,  0.5406493 , -0.30222824, -0.31411415,
         0.20628798,  0.3015111 ,  0.00452763, -0.16958264,  0.16370559],
       [-0.4316275 , -0.00383484,  0.1301375 , -0.00497335,  0.35229963,
        -0.533169  , -0.5395323 , -0.38931373,  0.37550664,  0.11691719],
       [ 0.48825824, -0.5137391 ,  0.09484595,  0.17481089, -0.07436872,
        -0.34214374, -0.45051283,  0.17555529,  0.17630273,  0.33806115],
       [-0.39855343, -0.4161104 ,  0.04913497, -0.0080325 , -0.26898718,
        -0.31455696, -0.4873821 , -0.46886253, -0.5088423 ,  0.525043  ],
       [-0.14787078, -0.4739742 ,  0.01502061, -0.3181085 , -0.511928  ,
         0.56974995, -0.07310396, -0.5635974 ,  0.30465543,  0.12058783],
       [-0.3865164 , -0.33317468, -0.39082003, -0.22275722,  0.31269085,
         0.47852027,  0.355474  , -0.30767608,  0.22329861, -0.4574796 ],
       [-0.2509699 , -0.57076806, -0.45308483,  0.08860171

3、索引与切片


In [7]:
a=tf.range(4)
a1=a[3::-2]
print(a1)


tf.Tensor([3 1], shape=(2,), dtype=int32)


In [8]:
b=tf.gather(a,indices=[0,3])
print(b)

tf.Tensor([0 3], shape=(2,), dtype=int32)


维度变换

In [9]:
a=tf.ones([4,28,28,3])
print(tf.expand_dims(a,axis=-1).shape)
b=tf.ones([1,2,3,1,1])
print(tf.squeeze(b).shape)
print(tf.squeeze(b,axis=0).shape)

(4, 28, 28, 3, 1)
(2, 3)
(2, 3, 1, 1)


broadCast 广播


In [10]:
import sys

In [11]:
a=tf.ones([3,4])
a1=tf.broadcast_to(a,[2,3,4])
print(sys.getsizeof(a1))
a2=tf.expand_dims(a,axis=0)
a2=tf.tile(a2,[2,1,1])
print(sys.getsizeof(a2))

168
168
