In [2]:
import tensorflow as tf
import numpy as np

1.dateType of tensorFlow

In [3]:
a=tf.constant(1.)
print(a)
print(a.ndim)
print(a.device)

tf.Tensor(1.0, shape=(), dtype=float32)
0
/job:localhost/replica:0/task:0/device:CPU:0


2.create tensor


In [4]:
b=np.arange(5)
bb=tf.convert_to_tensor(b,dtype=tf.float32)
print(bb)
bbb=tf.cast(bb,dtype=tf.int32)
print(bbb)
b_var=tf.Variable(bb,name='test_arg')
print("name:"+b_var.name)

tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
name:test_arg:0


In [5]:
c=tf.zeros([2,3,3],dtype=tf.int32)
d=tf.zeros_like(c)
print(d)
c=tf.ones([2,3,3],dtype=tf.int32)
print(c)
d=tf.fill([2,3,3],9)
print(d)

tf.Tensor(
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[9 9 9]
  [9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]
  [9 9 9]]], shape=(2, 3, 3), dtype=int32)


In [6]:
out=tf.random.uniform([4,10],name='out')
y=tf.range(4)
y=tf.one_hot(y,depth=10)
loss=tf.keras.losses.MSE(y,out)
print(loss)
loss=tf.reduce_mean(loss)
print(loss)


tf.Tensor([0.29997283 0.3700024  0.23614883 0.6134377 ], shape=(4,), dtype=float32)
tf.Tensor(0.37989044, shape=(), dtype=float32)


In [7]:
x=tf.random.normal([4,8])
net=tf.keras.layers.Dense(10)
net.build((4,8))
print(net.kernel)  # 所使用的变换举证
print(net(x).shape)
print(net.bias.shape)

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[ 0.29147512,  0.51963377, -0.3467219 , -0.51204944,  0.57307315,
         0.11224836, -0.23410517, -0.14214644,  0.20699275, -0.45291746],
       [ 0.30260497, -0.25970468,  0.13881445,  0.25123543,  0.44785142,
         0.36035693,  0.56552553,  0.40435606,  0.51295674,  0.35151982],
       [ 0.15863454, -0.4317229 , -0.16692251,  0.3483305 ,  0.44755626,
        -0.13063744, -0.25851524,  0.5551714 , -0.340909  ,  0.06552798],
       [-0.25729153, -0.3721503 ,  0.10217476,  0.13250893,  0.55786633,
         0.23266023, -0.42103678,  0.38596082,  0.54700196, -0.43202546],
       [ 0.3004151 ,  0.51184976, -0.10883337, -0.33648682, -0.05753511,
        -0.14869696, -0.37020004, -0.19547892, -0.1850648 ,  0.49225628],
       [ 0.20211673, -0.48155162, -0.39172882, -0.527132  , -0.5191398 ,
        -0.5207232 ,  0.19836819,  0.3545943 , -0.21752277,  0.08129185],
       [-0.07283264,  0.5272076 ,  0.50057006,  0.04678303

3、索引与切片


In [8]:
a=tf.range(4)
a1=a[3::-2]
print(a1)


tf.Tensor([3 1], shape=(2,), dtype=int32)


In [9]:
b=tf.gather(a,indices=[0,3])
print(b)

tf.Tensor([0 3], shape=(2,), dtype=int32)


维度变换

In [12]:
a=tf.ones([4,28,28,3])
print(tf.expand_dims(a,axis=-1).shape)
b=tf.ones([1,2,3,1,1])
print(tf.squeeze(b).shape)
print(tf.squeeze(b,axis=0).shape)

(4, 28, 28, 3, 1)
(2, 3)
(2, 3, 1, 1)


broadCast 广播


In [28]:
import sys

In [29]:
a=tf.ones([3,4])
a1=tf.broadcast_to(a,[2,3,4])
print(sys.getsizeof(a1))
a2=tf.expand_dims(a,axis=0)
a2=tf.tile(a2,[2,1,1])
print(sys.getsizeof(a2))

168
168
