In [11]:
import tensorflow as tf
import numpy as np

1.dateType of tensorFlow

In [9]:
a=tf.constant(1.)
print(a)
print(a.ndim)
print(a.device)

tf.Tensor(1.0, shape=(), dtype=float32)
0
/job:localhost/replica:0/task:0/device:CPU:0


2.create tensor


In [14]:
b=np.arange(5)
bb=tf.convert_to_tensor(b,dtype=tf.float32)
print(bb)
bbb=tf.cast(bb,dtype=tf.int32)
print(bbb)
b_var=tf.Variable(bb,name='test_arg')
print("name:"+b_var.name)

tf.Tensor([0. 1. 2. 3. 4.], shape=(5,), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
name:test_arg:0


In [18]:
c=tf.zeros([2,3,3],dtype=tf.int32)
d=tf.zeros_like(c)
print(d)
c=tf.ones([2,3,3],dtype=tf.int32)
print(c)
d=tf.fill([2,3,3],9)
print(d)

tf.Tensor(
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]], shape=(2, 3, 3), dtype=int32)


In [20]:
out=tf.random.uniform([4,10],name='out')
y=tf.range(4)
y=tf.one_hot(y,depth=10)
loss=tf.keras.losses.MSE(y,out)
print(loss)
loss=tf.reduce_mean(loss)
print(loss)


tf.Tensor([0.44635478 0.2595389  0.39031798 0.3252991 ], shape=(4,), dtype=float32)
tf.Tensor(0.3553777, shape=(), dtype=float32)


In [34]:
x=tf.random.normal([4,8])
net=tf.keras.layers.Dense(10)
net.build((4,8))
print(net.kernel)  # 所使用的变换举证
print(net(x).shape)
print(net.bias.shape)

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[ 0.02651668,  0.05898762, -0.32066494,  0.19428825, -0.5769244 ,
         0.34867805, -0.45171562,  0.570521  , -0.15838471,  0.42994106],
       [-0.52768093, -0.5020034 , -0.1903682 ,  0.3288238 , -0.45060217,
        -0.35785264, -0.18897215, -0.04983795,  0.27868068,  0.4080143 ],
       [ 0.19068205, -0.5674048 ,  0.2553659 , -0.38740587, -0.5759398 ,
         0.49910772, -0.0532766 , -0.27769938,  0.54793906,  0.33956677],
       [ 0.17284149, -0.05288059,  0.35460734,  0.425089  , -0.14174229,
         0.12381119,  0.16628462,  0.17596263,  0.41320348, -0.23338732],
       [ 0.4913628 ,  0.05592662,  0.46866155,  0.2859649 , -0.04250139,
         0.5724776 , -0.31121108,  0.05732769, -0.44693238, -0.2858808 ],
       [ 0.3906737 ,  0.16475767, -0.23243284,  0.07150048, -0.5429758 ,
        -0.19511938,  0.00455022, -0.20579681, -0.2516974 ,  0.35388356],
       [ 0.49580014,  0.57079947, -0.5008021 , -0.3262891 

3、索引与切片


In [38]:
a=tf.range(4)
a1=a[3::-2]
print(a1)


tf.Tensor([3 1], shape=(2,), dtype=int32)


In [41]:
b=tf.gather(a,indices=[0,3])
print(b)

tf.Tensor([0 3], shape=(2,), dtype=int32)


维度变换


In [43]:
a=tf.ones([4,28,28,3])
a=tf.reshape(a,[4,784,3])
print(a.shape)



InvalidArgumentError: Input to reshape is a tensor with 9408 values, but the requested shape has 1536 [Op:Reshape]