merge and split


In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a=tf.ones([2,3,4])
b=tf.ones([2,3,4])

In [3]:
c=tf.concat([a,b],axis=0)
c=tf.stack([a,b],axis=0)
print(c.shape)
c_unstack=tf.unstack(c,axis=3)
print(len(c_unstack))
c_split=tf.split(c,axis=3,num_or_size_splits=[1,1,2])
print(c_split)

(2, 2, 3, 4)
4
[<tf.Tensor: id=15, shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]], dtype=float32)>, <tf.Tensor: id=16, shape=(2, 2, 3, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]], dtype=float32)>, <tf.Tensor: id=17, shape=(2, 2, 3, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]], dtype=float32)>]


In [4]:
train_data=tf.constant([[0.7,0.2,0.1],[0.1,0.1,0.8]],dtype=tf.float32)
true_data=tf.constant([0,1],dtype=tf.int32)
label=tf.cast(tf.argmax(train_data,axis=1),dtype=tf.int32)
accruracy=tf.cast(tf.equal(label,true_data),dtype=tf.int32)
accruracy=tf.reduce_sum(accruracy)/2
print(accruracy)
c=tf.constant([1,1,2,3,1])
print(tf.unique(c))

tf.Tensor(0.5, shape=(), dtype=float64)
Unique(y=<tf.Tensor: id=32, shape=(3,), dtype=int32, numpy=array([1, 2, 3])>, idx=<tf.Tensor: id=33, shape=(5,), dtype=int32, numpy=array([0, 0, 1, 2, 0])>)


In [5]:
def accuracy(out_put,target,topk=(1,)):
    maxk=max(topk)
    batch_size=target.shape[0]
    pre=tf.math.top_k(out_put,maxk).indices
    pre=tf.transpose(pre,perm=[1,0])
    target=tf.broadcast_to(target,pre.shape)
    correct=tf.equal(pre,target)

    res=[]
    for k in topk:
        correct_k=tf.cast(tf.reshape(correct[:k],[-1]),dtype=tf.float32)
        correct_k=tf.reduce_sum(correct_k)
        acc=float(correct_k*(100/batch_size))
        res.append(acc)
    return res

out=tf.random.normal([10,6])
out=tf.math.softmax(out,axis=1)
label=tf.random.uniform([10],maxval=6,dtype=tf.int32,name='label')
print("prob:",out)
pred=tf.argmax(out,axis=1)
acc=accruracy(out,label,(1,2,3,4,5,6))
print(acc)

prob: tf.Tensor(
[[0.18914455 0.13127434 0.03753081 0.30878717 0.31056187 0.02270122]
 [0.07210293 0.04480904 0.40489176 0.29551548 0.03023243 0.15244836]
 [0.10895432 0.12371824 0.04331626 0.14372498 0.08741116 0.49287504]
 [0.26060507 0.4348102  0.14537288 0.08517645 0.05711546 0.01691996]
 [0.05670745 0.09924065 0.43651462 0.15052003 0.0642606  0.19275665]
 [0.03208768 0.08043952 0.46071807 0.23915523 0.1556175  0.03198198]
 [0.48821378 0.04107748 0.06420166 0.2652414  0.01533049 0.1259352 ]
 [0.7516881  0.00872512 0.0255622  0.04361488 0.08865239 0.08175732]
 [0.10207477 0.2619223  0.3989438  0.1407758  0.07333813 0.02294523]
 [0.03954028 0.2542945  0.3683925  0.06335633 0.1818135  0.09260288]], shape=(10, 6), dtype=float32)


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

填充和复制


In [6]:
aa=tf.pad(a,[[0,0],[1,1],[1,1]])
print(aa)
bb=tf.tile(b,[2,1,1])
print(bb.shape)

tf.Tensor(
[[[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 1. 1. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0.]]], shape=(2, 5, 6), dtype=float32)
(4, 3, 4)


张量限幅


In [ ]:
nums=tf.range(10,dtype=tf.int32)
print(tf.maximum(nums,3))

In [11]:
c=tf.random.normal([3,3],dtype=tf.float32)
print(c)
mask=c>0
print(mask)
indices=tf.where(mask)
print(indices)
res=tf.gather_nd(c,indices=indices)
print(res)

tf.Tensor(
[[ 1.9594563   0.9995384  -0.12404789]
 [ 1.6674773   0.43090057 -1.2981229 ]
 [ 0.10302886  0.6231257  -0.4341242 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ True  True False]
 [ True  True False]
 [ True  True False]], shape=(3, 3), dtype=bool)
tf.Tensor(
[[0 0]
 [0 1]
 [1 0]
 [1 1]
 [2 0]
 [2 1]], shape=(6, 2), dtype=int64)
tf.Tensor([1.9594563  0.9995384  1.6674773  0.43090057 0.10302886 0.6231257 ], shape=(6,), dtype=float32)


In [13]:
points=[]
x=tf.linspace(-2.,2,5)
print(x)


tf.Tensor([-2. -1.  0.  1.  2.], shape=(5,), dtype=float32)
